### ISSUE TITLE
IntelliJ IDEA 2021.2 EAP (Ultimate Edition) Build #IU-212.3116.43

### ISSUE THREAD

**Issue by Doaxan** [qeesung/HighlightBracketPair#25]
Do not work with:
```
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3116.43, built on May 27, 2021
IntelliJ IDEA EAP User
Expiration date: June 26, 2021
Runtime version: 11.0.11+9-b1460.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.12.5-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi.idea (15.1), Pythonid (212.3116.43), com.jetbrains.edu (2021.5-2021.1-713)
Kotlin: 212-1.4.32-release-IJ3116.43
Current Desktop: KDE
```

```Plugin 'io.github.qeesung.component.HighlightBracketPair' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: 
                io.github.qeesung.component.HighlightBracketPairApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=HighlightBracketPair, id=io.github.qeesung.component.HighlightBracketPair, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.3116.43.plugins/HighlightBracketPair, version=1.1.2, package=null), packagePrefix=null, instanceId=33, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:433)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:372)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:57)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:250)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:73)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:105)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:63)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:97)
    at com.intellij.ide.b.o.R.a(R.java:117)
    at com.intellij.ide.b.o.aQ.a(aQ.java:304)
    at com.intellij.ide.b.o.aQ.a(aQ.java:141)
    at com.intellij.ide.b.o.aQ.b(aQ.java:91)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.ide.b.o.aQ.a(aQ.java:90)
    at com.intellij.ide.b.j.e.a(e.java:95)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:91)
    at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:275)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)```

**Comment by dmytrobabeshko** [comment]
Hello,

The same issue:
```
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3116.43, built on May 27, 2021
IntelliJ IDEA EAP User
Expiration date: June 26, 2021
Runtime version: 11.0.11+9-b1460.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3500M
Cores: 16
Registry: compiler.build.report.statistics=true, debugger.watches.in.variables=false, go.run.processes.with.pty=false
Non-Bundled Plugins: com.dmitryzhelnin.intellij.plugin.gitextensions (0.4.3), com.fwdekker.randomness (2.7.0), com.intellij.ideolog (203.0.27.0), com.jetbrains.annotations.preloader (1.0.4), krasa.CpuUsageIndicator (1.14), org.ermadan.kafkalytic (0.9.13), mobi.hsz.idea.gitignore (4.1.1), org.toml.lang (0.2.147.3871-211), some.awesome (1.14), com.intellij.kubernetes (212.3116.29), Jetbrains TeamCity Plugin (2020.2.85899), String Manipulation (8.15.203.000.3), YourKit Java Profiler 2021.3-b230 Integration (2021.3.230.0), com.andrey4623.intellij.plugins.effectiveinnerbuilder (1.0), org.jetbrains.jumpToLine (0.1.6), org.sonarlint.idea (4.16.0.31683), com.perl5 (212-SNAPSHOT), com.dmarcotte.handlebars (212.3116.29), org.intellij.scala (2021.2.8), MetricsReloaded (1.11.2), izhangzhihao.rainbow.brackets (6.17), org.jetbrains.plugins.go (212.3116.29)
Kotlin: 212-1.4.32-release-IJ3116.43
```

**Comment by mrparag94** [comment]
All versions of 2021.2 have the same issue.

**Comment by luiscarielo83** [comment]
Same issue. Any solution?

**Comment by Klaus-Kin** [comment]
If you get some useful solution about it, reply to me pease.Thanks a lot

**Comment by luiscarielo83** [comment]
@monkeyKinn 
https://github.com/qeesung/HighlightBracketPair/issues/26#issuecomment-889242649

**Comment by uriloya** [comment]
use this maintained fork instead:
https://plugins.jetbrains.com/plugin/17320-highlightbracketpair
https://github.com/AprilViolet/highlight-bracket-pair
