### ISSUE TITLE
It does not work in version 2021.2

### ISSUE THREAD

**Issue by xiaobu1994** [qeesung/HighlightBracketPair#27]
lugin 'io.github.qeesung.component.HighlightBracketPair' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: 
                io.github.qeesung.component.HighlightBracketPairApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=HighlightBracketPair, id=io.github.qeesung.component.HighlightBracketPair, descriptorPath=plugin.xml, path=D:\Tool\IntelliJ IDEA 2021.2\.IntelliJIdea\config\plugins\HighlightBracketPair, version=1.1.2, package=null), packagePrefix=null, instanceId=35, state=active)

**Comment by strpc** [comment]
@xiaobu1994 
https://github.com/qeesung/HighlightBracketPair/issues/26#issuecomment-889242649

**Comment by xiaobu1994** [comment]
> @xiaobu1994
> [#26 (comment)](https://github.com/qeesung/HighlightBracketPair/issues/26#issuecomment-889242649)

thanks

**Comment by SirTwsted** [comment]
I can confirm,  this is also happening in Pycharm 2021.2

`
Plugin 'io.github.qeesung.component.HighlightBracketPair' failed to initialize and will be disabled. Please restart PyCharm.

java.lang.ClassNotFoundException: 
                io.github.qeesung.component.HighlightBracketPairApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=HighlightBracketPair, id=io.github.qeesung.component.HighlightBracketPair, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2021.2\plugins\HighlightBracketPair, version=1.1.2, package=null), packagePrefix=null, instanceId=17, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
    at com.a.d.b.b.ay.a(ay.java:62)
    at com.a.d.b.b.ag.a(ag.java:119)
    at com.a.d.b.b.Y.a(Y.java:310)
    at com.a.d.b.b.Y.b(Y.java:143)
    at com.a.d.b.b.Y.a(Y.java:93)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.a.d.b.b.Y.a(Y.java:92)
    at com.a.d.b.b.Z.a(Z.java:58)
    at com.intellij.idea.MainImpl.start(MainImpl.java:18)
    at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

PyCharm 2021.2 (Community Edition)
Build #PC-212.4746.96, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.experimental.ui.toolwindow.stripes=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.dubreuia (2.2.0), com.andrey4623.rainbowcsv (2.0), com.github.lppedd.idea-return-highlighter (0.8.1), com.softwareco.intellij.plugin (2.4.9), manjaro.mpb (1.6), manjaro.spb (1.1), net.seesharpsoft.intellij.plugins.csv (2.17.1), net.vektah.codeglance (1.5.4), com.mallowigi (38.0.0), izhangzhihao.rainbow.brackets (6.19), some.awesome (1.14), startrek-progressbar (1.0.0), com.chrisrm.idea.MaterialThemeUI (6.8.0.1), R4Intellij (212.4535.4), aws.toolkit (1.30-212), com.github.ArtsiomCh.NestedBracketsColorer (0.5.0)

**Comment by Mingw0717** [comment]
In my environment also happened this error .
It seems that has not been maintained long time.
